version: '3'
services:
  app:
    image: fastify-try-5
    ports:
      - 8080:8080
    environment:
      POSTGRES_PASSWORD: postgres123
      POSTGRES_HOST: host.docker.internal
      POSTGRES_PORT: 5433
      POSTGRES_SHCEMA: postgresql_docker

  postgres:
    image: postgres:16
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: postgres123
